version: '3.3'

services:
  django-pepper:
    build: 
      context: ../pepper/
      dockerfile: Dockerfile.prod
    command: gunicorn pepper.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume_pepper:/home/pepper/web/staticfiles
    expose:
      - 8000
    env_file:
      - ../common-prod-env/.env.pepper.prod
  django-clove:
    build: 
      context: ../clove/
      dockerfile: Dockerfile.prod
    command: gunicorn clove.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - static_volume_clove:/home/clove/web/staticfiles
    expose:
      - 8001
    env_file:
      - ../common-prod-env/.env.clove.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_clove:/var/lib/postgresql/data/
    env_file:
      - ../common-prod-env/.env.clove.prod.db
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.fe.prod
    volumes:
      - static_volume_pepper:/home/pepper/web/staticfiles
      - static_volume_clove:/home/clove/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - django
volumes:
  postgres_data_clove:
  static_volume_pepper:
  static_volume_clove: